### ISSUE TITLE
Allow drupal/filehash:^3

### ISSUE THREAD

**Issue by kayakr** [Islandora/islandora#1005]
Filehash 3.0.1 is out https://www.drupal.org/project/filehash/releases/3.0.1

Islandora is hard-coded in composer.json to only support `filehash:^2` https://github.com/Islandora/islandora/blob/2.x/composer.json#L21

I suggest supporting both, e.g. `filehash: ^2 || ^3`

**Comment by rosiel** [comment]
[I was bitten](https://github.com/Islandora/islandora/pull/912) by not testing the previous major update of filehash properly.

So I just want to outline what needs to be tested:

When we update a file (/media), islandora code tests whether the filehash has changed, and does not run derivatives if it's got the same `sha1`. 

The code: https://github.com/Islandora/islandora/blob/2.11.0/islandora.module#L185-L188

**Comment by jordandukart** [comment]
Closing as this merged in https://github.com/Islandora/islandora/pull/1016.
