### ISSUE TITLE
[TECH DEBT] Revisit why we are using Features for Islandora Core Feature

### ISSUE THREAD

**Issue by rosiel** [Islandora/islandora#902]
**Overview of feature request**
 
 Is Features the right solution for Islandora Core Feature?

Do the affordances of Features (namely: updates) fit with how we are using this module in practice? Do we want to write any guidance for site owners?

**Comment by wgilling** [comment]
I did not intend to link this from the hOCR ticket... I was in my terminal and typed "exit" but the browser had focus and it opened the "x" key opened the Development dialog and the "it" did the search for this task -- and enter submitted that as a linked PR for this issue. I cannot see how to remove that link between these two.

**Comment by seth-shaw-asu** [comment]
Burn it. 🔥

**Comment by seth-shaw-asu** [comment]
Commenting to resurface this issue. Features is a vestigial dependency. Purge it.
