### ISSUE TITLE
[Tech Debt] EVA 2.x is no longer supported

### ISSUE THREAD

**Issue by dannylamb** [Islandora/islandora#915]
We should upgrade to 3.x to stay current.  We're getting these on Drupal status reports, and because it's pinned to 2.x in Islandora and Islandora Defaults, composer won't update it.

![image](https://user-images.githubusercontent.com/20773151/205386214-30542a57-6cbd-4fc7-981e-c7d7e12ac37c.png)

![image](https://user-images.githubusercontent.com/20773151/205386237-8da98e71-f3cc-4c78-a266-0e545a5d92ed.png)

**Comment by rosiel** [comment]
https://github.com/Islandora/islandora/pull/911 ?
