### ISSUE TITLE
Fix code using deprecated Symfony Event class

### ISSUE THREAD

**Issue by seth-shaw-asu** [Islandora/islandora#927]
Way back [in Drupal 9.1 they deprecated the Symfony Event class](https://www.drupal.org/node/3159012). The update required swapping arguments in the dispatch function. So, our site still works with D9 but will fail with D10. The JWT module just fixed this for themselves last week with [their 1.1 release](https://www.drupal.org/project/jwt/releases/8.x-1.1).

More immediately, however, enabling the current standalone version of [webprofiler ](https://www.drupal.org/project/webprofiler) will cause the site to choke on the deprecation; e.g.:
```
[error] 19883#19883: *139901 FastCGI sent in stderr: "PHP message: TypeError: Argument 1 passed to "Symfony\Contracts\EventDispatcher\EventDispatcherInterface::dispatch()" must be an object, string given. in /var/www/html/drupal/web/modules/contrib/webprofiler/src/EventDispatcher/TraceableEventDispatcher.php on line 84 #0 /var/www/html/drupal/web/modules/contrib/islandora/src/EventGenerator/EmitEvent.php(163): Drupal\webprofiler\EventDispatcher\TraceableEventDispatcher->dispatch()
#1 /var/www/html/drupal/web/core/lib/Drupal/Core/Action/ActionBase.php(22): Drupal\islandora\EventGenerator\EmitEvent->execute()
#2 /var/www/html/drupal/web/core/modules/system/src/Entity/Action.php(129): Drupal\Core\Action\ActionBase->executeMultiple()
#3 /var/www/html/drupal/web/modules/contrib/islandora/src/PresetReaction/PresetReaction.php(59): Drupal\system\Entity\Action->execute()
#4 /var/www/html/drupal/web/modules/contrib/islandora/src/IslandoraUtils.php(329): Drupal\islandora\PresetReaction\PresetReaction->execute()
#5 /var/www/html/drupal/web/modules/contrib/islan" while reading response header from upstream, server: keep-qa.lib.asu.edu, request: "POST /node/172545/edit HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "keep-qa.lib.asu.edu", referrer: "https://keep-qa.lib.asu.edu/node/172545/edit"
```
Using the current version of webprofiler requires a fix now.

Side-note: if you enable webprofiler you are likely to get similar errors for other out-of-date modules. Both facets and workbench_email needed updates to work.

**Comment by jordandukart** [comment]
Fixed in https://github.com/Islandora/islandora/pull/928.
