### ISSUE TITLE
[BUG] WSOD when viewing object

### ISSUE THREAD

**Issue by dannylamb** [Islandora/islandora#934]
Looks like in Crayfish Commons 3.0, a service that's used in Drupal got removed and we still require it for populating the Fedora URI pseudofield. 

**What steps does it take to reproduce the issue?**
Try to view an object or an Original File media.

* When does this issue occur?
Anytime you view an object

* Which page does it occur on?
Any object or media page

* What happens?
You get a whitescreen

* To whom does it occur (anonymous visitor, editor, administrator)?
Anyone

* What did you expect to happen?
To see the object

**Which version of Islandora are you using?**
2.7.0

**Any related open or closed issues to this bug report?**
Nope

**Comment by adam-vessey** [comment]
The [given class still exists in 3.x](https://github.com/Islandora/Crayfish-Commons/blob/64f0c7cdc0a49221688a1df4c5cb728085564327/EntityMapper/EntityMapper.php), so... what exact error is popping?

Or do you have stuff applied from the separation effort in https://github.com/Islandora/documentation/issues/2220, which isn't quite finalized, or... yeah, don't really feel there enough info here.

**Comment by dannylamb** [comment]
Exact error from the Drupal logs just states that the service is no longer there: 

```
drupal_1      | 2023-03-30T18:38:07.730070601Z 2023/03/30 18:38:07 [error] 1370#1370: *32 FastCGI sent in stderr: "PHP message: Error: Class 'Islandora\Crayfish\Commons\EntityMapper\EntityMapper' not found in /var/www/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 259 #0 /var/www/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\Container->createService()
drupal_1      | 2023-03-30T18:38:07.730127842Z #1 /var/www/drupal/web/core/lib/Drupal.php(207): Drupal\Component\DependencyInjection\Container->get()
drupal_1      | 2023-03-30T18:38:07.730141699Z #2 /var/www/drupal/web/modules/contrib/islandora/islandora.module(639): Drupal::service()
drupal_1      | 2023-03-30T18:38:07.730151721Z #3 [internal function]: islandora_entity_view()
drupal_1      | 2023-03-30T18:38:07.730160814Z #4 /var/www/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(426): call_user_func_array()
drupal_1      | 2023-03-30T18:38:07.730169853Z #5 /var/www/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(405): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}()
drupal_1      | 2023-03-30T18:38:07.730185956Z #6 /var/www/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(433): Drupal\Core\Extension\ModuleHandler->invokeAllWith()
drupal_1      | 2023-03-30T18:38:07.730204044Z #7 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(289): Drupal\Core\Extension\ModuleHandler->invokeAll()
drupal_1      | 2023-03-30T18:38:07.730214526Z #8 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(239): Drupal\Core\Entity\EntityViewBuilder->buildMultiple()
drupal_1      | 2023-03-30T18:38:07.730224454Z #9 [internal function]: Drupal\Core\Entity\EntityViewBuilder->build()
drupal_1      | 2023-03-30T18:38:07.730233657Z #10 /var/www/drupal/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(101): call_user_func_array()
drupal_1      | 2023-03-30T18:38:07.730243995Z #11 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(788): Drupal\Core\Render\Renderer->doTrustedCallback()
drupal_1      | 2023-03-30T18:38:07.730256711Z #12 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(374): Drupal\Core\Render\Renderer->doCallback()
drupal_1      | 2023-03-30T18:38:07.730323365Z #13 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender()
drupal_1      | 2023-03-30T18:38:07.730347421Z #14 /var/www/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(242): Drupal\Core\Render\Renderer->render()

```

**Comment by adam-vessey** [comment]
Which then prompts: What version of Crayfish-Commons are you actually running, given the class is still present [in the latest 3.x release](https://github.com/Islandora/Crayfish-Commons/blob/3.0.0/EntityMapper/EntityMapper.php)? Like, running premerged PRs still in progress, or a fork? Any patches applied?

**Comment by dannylamb** [comment]
No fork nor patches :shrug: 

If the service still exists maybe this is a composer thing?

**Comment by adam-vessey** [comment]
Yeah, could be something like the autoloader needing to be rebuilt, or Drupal's/Drush's cache, or possibly just the webserver needing a restart to flush caches.

Flush ALL the caches! :V

**Comment by dannylamb** [comment]
Yeah wow crazy.  `composer require islandora/islandora:2.7.0` actually deletes my crayfish-commons directory!

**Comment by dannylamb** [comment]
Not an Islandora thing per se.  If it turns out it's how it got into packagist or something I'll make a separate ticket.  Closing this.  Thanks for the help @adam-vessey :bow:
