### ISSUE TITLE
[FEATURE] IIIF Manifests should get hOCR from related media with a given tag

### ISSUE THREAD

**Issue by alxp** [Islandora/islandora#946]
*PR to come*

The IIIF Manifest can now retrieve hOCR that is stored in a field on the image or file media types, i.e., multi-file media.

We should also make it an option to specify that hOCR is located on a different media attached to the parent node, identified by a Media Use tag.
 
**What kind of user is the feature intended for?** Site builder 
 
 
**What inspired the request?**
 
 
**Any brand new behavior do you want to add to Islandora?**

A new configuration field on the islandora_iiif Views Style plugin for specifying a term that holds the hOCR
A Media Use tag for hOCR

**Comment by rosiel** [comment]
Available in islandora 2.12.
