### ISSUE TITLE
[FEATURE] Add tokens to get Original File filename, extension

### ISSUE THREAD

**Issue by alxp** [Islandora/islandora#947]
PR Forthcoming.

**Overview of feature request**

Add new tokens to Islandora to get th Original File's file name, extension.
 
 
**What kind of user is the feature intended for?**
Site builder 
 
 
**What inspired the request?**
 
We would like to have derivative files share the same file name as the original uploaded files. This info is currently not available to the token system.
 
**Any brand new behavior do you want to add to Islandora?**
 
 New tokens

**Comment by rosiel** [comment]
Confirmed, the linked PR did this.
