### ISSUE TITLE
[FEATURE] Islandora IIIF: Allow for relative file paths in IIIF manifests

### ISSUE THREAD

**Issue by alxp** [Islandora/islandora#964]
**Overview of feature request**
 
 
**What kind of user is the feature intended for?**
Systems administrator
 
 
**What inspired the request?**
 When testing the Drupal 10 compatibility of Islandora Mirador, I set up a simple local stack with an instance of Cantaloupe 5.0 running on my local computer.

Since it was local, I configured it to serve files directly from the Drupal sites/default/files folder rather than making web requests.

This would be a useful feature for performance improvement for installs where Cantaloupe can run on the same machine as Drupal.
 
**What existing behavior do you want changed?**
 
Add a config setting to let the site owner choose to have the IIIF Manifest include relative paths.
 
Follow this setting when generating IIIF manifests.

**Any brand new behavior do you want to add to Islandora?**
 
 
**Any related open or closed issues to this feature request?**

**Comment by rosiel** [comment]
Is there any documentation needed for this? For example, does Cantaloupe need to be configured to know where paths are relative to (the drupal root directory, perhaps?)

**Comment by alxp** [comment]
@rosiel If/when we decide to separate out Islandora IIIF from Islandora then it would make sense to have a section in the README on setting up a basic Cantaloupe install.
